spring:
  application:
    name: jpashop
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jpa
    password: jpa
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
